version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escolas
    networks:
      - mysql_net
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    depends_on:
      - mysql
      - redis
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - 80
    restart: always
    networks:
      - mysql_net
    links:
      - mysql
      - redis
  auth:
    depends_on:
      - mysql
      - redis
    build:
      context:  ./auth
      dockerfile: Dockerfile
    expose:
      - 80
    restart: always
    networks:
      - mysql_net
    links:
      - mysql
      - redis
  proxy:
    build:
      context:  ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - auth
    links:
      - app
    networks:
      - mysql_net
volumes:
  mysql_data:
networks:
  mysql_net:
    driver: bridge
