version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escolas
    networks:
      - mysql_net
  app:
    depends_on:
      - mysql
    image: laravel:latest
    container_name: laravel
    ports:
      - "80:80"
    restart: always
    networks:
      - mysql_net
    links:
      - mysql
volumes:
    mysql_data:
networks:
  mysql_net:
    driver: bridge
